version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: edupredict-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: edupredict
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - edupredict-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: edupredict-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - edupredict-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edupredict-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/edupredict?authSource=admin
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-key-here-change-in-production-12345678901234567890
      - DEBUG=true
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
    networks:
      - edupredict-network

volumes:
  mongodb_data:
  redis_data:

networks:
  edupredict-network:
    driver: bridge